### PR TITLE
Support 'dcos cassandra node' args of the form '1234' OR 'node-1234'

### PR DESCRIPTION
**Pull request by nickbp**

### CODE REVIEW

**Comment by nickbp** [comment]
CC Keith on account of the (slight) user interface change

**Comment by mohitsoni** [comment]
LGTM!

**Comment by nickbp** [comment]
From discussion earlier it sounds like the desired behavior would be to show a deprecation warning for the old integer values, and the 'node_id' param should instead be displayed as 'task_name'.

**Comment by nickbp** [comment]
Aforementioned changes have now been made.

**Pull request merged**
