### PR TITLE
Dse 5.0.0

### PR DESCRIPTION
**Pull request by kow3ns**

### CODE REVIEW

**Comment by keithchambers** [comment]
@kow3ns if this is merged to master will vinilla Apache Cassandra still work?

Uber shared today that they have multiple production deployments on Cassandra 2.2.X. For new deployments they plan to use 3.0.X but they still need to maintain the existing deployments on 2.2.X.

Bottom line - we'll need a strategy for supporting 2.2.X, 3.0.X, and DSE 5.X.

**Comment by cornelf** [comment]
👍

**Comment by kow3ns** [comment]
retest this please

**Comment by kow3ns** [comment]
retest this please

**Comment by nickbp** [comment]
Going by how a lot of the code changes appear to be config related, might be able to have an empty/optional 'dse' section in the default yaml configs, and then fill in the config objects from the `DSE_` envvars dynamically in code? This could also allow dynamically switching between 'DSE mode' vs 'Apache mode' since it'd mostly be handled in code anyway.

I was able to do something similar for kafka's handling of KAFKA_OVERRIDE_* values, where it doesn't need any specific override settings in the default yaml, and instead just automatically grabs the override values from envvars when the config doesn't have any explicitly set: https://github.com/mesosphere/dcos-kafka-service/pull/242/files#diff-4042f7d0bef53bd920ae2006b10e595eR51

**Comment by kow3ns** [comment]
retest this please

**Comment by kow3ns** [comment]
retest this please

**Comment by kow3ns** [comment]
retest this please

**Comment by kow3ns** [comment]
retest this please

**Comment by kow3ns** [comment]
retest this please

**Pull request closed without merging**
