### PR TITLE
Add unit test case for pull request #246

### PR DESCRIPTION
**Pull request by szhou1234**
Ideally I should able to add a few asserts in testStartTerminated() to cover my fix. However, testStartTerminated() is broken and if you debug to see the behavior, it doesn't really go to the below branch in CassandraDaemonBlock#start:
`else  if (container.isTerminated() || container.isLaunching())`

So in this case, I have to create my own test case and make it as independent as possible, if you want to refactor the unit test cases later on.

### CODE REVIEW

**Comment by gabrielhartmann** [comment]
@mesosphere-ci: retest this please

**Comment by mrbrowning** [comment]
Hi @szhou1234, I just created [#250](https://github.com/mesosphere/dcos-cassandra-service/pull/250), which now causes the logic in `replaceTask` to be exercised when `testStartTerminated` is run. That should allow you to put the assertions in that test like you mentioned.

**Comment by gabrielhartmann** [comment]
@szhou1234, #250 is now merged.  Thanks for making that fix @mrbrowning.

**Comment by szhou1234** [comment]
Great. I'll update my diff accordingly.

**Comment by szhou1234** [comment]
@gabrielhartmann I updated the pull request. Please help take a look.

**Comment by gabrielhartmann** [comment]
@mesosphere-ci: retest this please.

**Comment by szhou1234** [comment]
To avoid using Whitebox, we'll have to refactor CassandraDaemonBlock and the test class to properly inject/mock the dependencies.

**Comment by gabrielhartmann** [comment]
@szhou1234:  Thanks a lot.

**Pull request merged**
