### PR TITLE
Fix EMC ECS compatibility

### PR DESCRIPTION
**Pull request by gabrielhartmann**

### CODE REVIEW

**Comment by ssk2** [comment]
mesosphere-ci: retest this please

**Comment by gabrielhartmann** [comment]
@mesosphere-ci: retest this please

**Comment by gabrielhartmann** [comment]
@mesosphere-ci: please restest this

**Comment by nickbp** [comment]
retest this please

**Comment by nickbp** [comment]
Note: It's likely that the s3 backup test will fail as the current test is just using the build number. The build numbers across root tests and mount tests currently match so they likely end up colliding?

**Comment by mohitsoni** [comment]
Build's failing because of:
`Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

**Comment by mohitsoni** [comment]
@mesosphere-ci: Please retest this.

**Pull request merged**
