### PR TITLE
[INFINITY-1448] Vendorise dependency on dcos-commons/cli.

### PR DESCRIPTION
**Pull request by ssk2**
Similar to https://github.com/mesosphere/dcos-kafka-service/pull/364.

### CODE REVIEW

**Comment by jsrodman** [comment]
For some reason i thought you were proposing moving the cli to its own repo.  Can you update the title here to [JIRA-NUM] to reference the background and/or add the background here?

**Comment by ssk2** [comment]
Sure, will create a JIRA. Turns out we didn't need to create a separate repo (`govendor` allows you to pull in a folder from within a repo - so we can leave the CLI code where it is for now).

**Comment by ssk2** [comment]
NB: I have manually verified this continues to build and is using the correct (vendored) dependency.

**Comment by nickbp** [comment]
retest this please

**Comment by ssk2** [comment]
retest this please

**Comment by ssk2** [comment]
@nickbp: CI is failing due to related tests. What would you like me to do here?

**Comment by nickbp** [comment]
Checked the failures. I think we can just push it through.

**Pull request merged**
