### PR TITLE
Add build publish feature for uploading artifacts

### PR DESCRIPTION
**Pull request by cooldoger**
It enables the customer to publish artifacts to maven repository with command:
`$ gradle clean publish`

### CODE REVIEW

**Comment by gabrielhartmann** [comment]
@mesosphere-ci: retest this please

**Comment by verma7** [comment]
@mohitsoni @gabrielhartmann Can we get this reviewed and merged?

**Comment by mohitsoni** [comment]
retest this please

**Comment by mohitsoni** [comment]
@mesosphere-ci retest this please

**Comment by mohitsoni** [comment]
@cooldoger Can you please resolve conflicts for build.gradle ?

**Comment by mohitsoni** [comment]
@mesosphere-ci retest this please.

**Comment by cooldoger** [comment]
Merged to master. Please review.

**Comment by cooldoger** [comment]
ping.

**Comment by verma7** [comment]
Ping!

**Comment by nickbp** [comment]
retest this please

**Comment by nickbp** [comment]
Could you rebase this on master? It's hitting test failures as it lacks #313

**Comment by cooldoger** [comment]
Rebased to master.

**Comment by cooldoger** [comment]
@nickbp @mohitsoni Could you please check the Jenkins and test:rootdisk test failures?

**Comment by nickbp** [comment]
Yep looking at it now. Other PRs are hitting similar issues.

**Comment by nickbp** [comment]
retest this please (did some work cleaning up test flakes, should be good now(?))

**Comment by cooldoger** [comment]
@nickbp could you please merge the change, seems the tests are all passed.

**Comment by nickbp** [comment]
Sure!

**Pull request merged**
