### PR TITLE
Make repair job incremental

### PR DESCRIPTION
**Pull request by szhou1234**
Repair job should be incremental to avoid affecting production workload.

### CODE REVIEW

**Comment by szhou1234** [comment]
@kow3ns can you merge this one? Thanks.

**Comment by gabrielhartmann** [comment]
@mesosphere-ci: retest this please.

**Comment by szhou1234** [comment]
@gabrielhartmann could you merge this? it has been sitting here for two weeks.

**Comment by gabrielhartmann** [comment]
@mesosphere-ci: retest this please

**Comment by gabrielhartmann** [comment]
@szhou1234:  Apologies for delay.  Kicked off CI now.  Will make sure this gets merged.

**Comment by gabrielhartmann** [comment]
@szhou1234: Opened PR #278.  Looks like your branch can't be updated to `master`.

**Comment by gabrielhartmann** [comment]
@szhou1234: Merged other PR #278

**Pull request closed without merging**
