### PR TITLE
Make repair job incremental

### PR DESCRIPTION
**Pull request by szhou1234**
Repair job should be incremental to avoid affecting production workload.

### CODE REVIEW

**Comment by szhou1234** [comment]
This pull request needs to be updated. I messed up it with a previous pull request.

**Comment by gabrielhartmann** [comment]
@mesosphere-ci: retest this please

**Comment by gabrielhartmann** [comment]
@mesosphere-ci: retest this please

**Comment by kow3ns** [comment]
Can you please update form master. Thank you.

**Comment by szhou1234** [comment]
created another pull request from master @kow3ns 
https://github.com/mesosphere/dcos-cassandra-service/pull/258

**Pull request closed without merging**
