### PR TITLE
sets verify to false in the global requests session in integration tests

### PR DESCRIPTION
**Pull request by kow3ns**

### CODE REVIEW

**Comment by mohitsoni** [comment]
LGTM!

**Comment by nickbp** [comment]
It looks like we can call the 'dcos.http.[get|put]' methods in the 'dcos' library and have them handle tokens/auth for us entirely. Trying this out locally...

**Comment by nickbp** [comment]
The way dcos-tests dealt with this was to have all 'requests' calls go through a single function, which set verify=False on all calls.

**Comment by nickbp** [comment]
See above commit -- lets see if this works...

**Comment by nickbp** [comment]
Ok, shakedown is now passing! The remaining error is a problem in the tooling when running dcos-tests afterwards. The tooling tries to add the same stub-universe to the cluster a second time, which the cluster refuses:

```
Adding repository: testpkg-jczohtrm https://infinity-artifacts.s3.amazonaws.com/autodelete7d/cassandra/20160914-212035-DCsCTAOrx6t1NIDx/stub-universe-cassandra.zip
Repository URI [https://infinity-artifacts.s3.amazonaws.com/autodelete7d/cassandra/20160914-212035-DCsCTAOrx6t1NIDx/stub-universe-cassandra.zip] is already present in the list
[STATUS] test:rootdisk error: CLI Setup failed
```

I need to update the tooling to handle that scenario. In the meantime for this PR: LGTM

**Comment by nickbp** [comment]
retest this please

**Comment by kow3ns** [comment]
retest this please

**Comment by kow3ns** [comment]
Merging this to progress forward on getting tests working again

**Pull request merged**
