### PR TITLE
#290 Executor is orphaned if Cassandra fails to initialize

### PR DESCRIPTION
**Pull request by dylanwilder**
The current offered solution is to abort the driver if there is a failure during Task creation.  However, this is only a half the solution as any error in the task factory will cause the scheduler to lose track of the executor.  A more comprehensive solution probably requires changes in the scheduler to manage executor state.

### CODE REVIEW

**Comment by triclambert** [comment]
@mesosphere-ci retest this please

**Comment by triclambert** [comment]
@mesosphere-ci retest this please

**Comment by dylanwilder** [comment]
thanks @triclambert, is that required to trigger the tests?

**Comment by triclambert** [comment]
Yes it is.

**Comment by dylanwilder** [comment]
Ref: [dcos-commons issue](https://github.com/mesosphere/dcos-commons/issues/293). These changes would allow us to make more holistic improvements here, rather than this small patch.

**Comment by dylanwilder** [comment]
did anybody have a chance to review this?

**Comment by dylanwilder** [comment]
@mohitsoni @gabrielhartmann any issues here? This bug is kind of a deal breaker for production deployments and would prefer not to have to work off of a fork.

**Comment by dylanwilder** [comment]
@mesosphere-ci retest this please

**Comment by verma7** [comment]
@mesosphere-ci retest this please

**Review by nickbp — APPROVED** [review]

**Pull request merged**
