### PR TITLE
Test n bug

### PR DESCRIPTION
**Pull request by mohitsoni**
Cluster Tasks were not correctly being generated from pre-existing reserved resource templates.  A test was written which appropriately failed.  Code changes were made such that the test now passes.

### CODE REVIEW

**Comment by colin-msphere** [comment]
retest this please

**Comment by colin-msphere** [comment]
retest this please

**Comment by mohitsoni** [comment]
@mesosphere-ci Please retest!

**Comment by colin-msphere** [comment]
retest this please

**Pull request merged**
