### PR TITLE
Storage util final

### PR DESCRIPTION
**Pull request by vargup**
Made StorageUtil class as final, as java does not support static at top level. And fix the issue with cassandra-rackdc.properties at .gitignore.

### CODE REVIEW

**Comment by triclambert** [comment]
@mesosphere-ci retest this please

**Comment by vargup** [comment]
@triclambert Can you please re-run the build or pass along the test failure info?

**Comment by mohitsoni** [comment]
@mesosphere-ci retest this please

**Comment by vargup** [comment]
please re-run the build.

**Comment by triclambert** [comment]
@mesosphere-ci retest this please

**Comment by mohitsoni** [comment]
@mesosphere-ci retest this please.

**Comment by mohitsoni** [comment]
@vargup Thanks for the PR!

**Pull request merged**
