### PR TITLE
Handling the 503 correctly

### PR DESCRIPTION
**Pull request by mohitsoni**
DCOS http module throws DCOSHTTPException, when an HTTP response code is not 2XX. This exception causes CLIs to spit out Python Tracebacks.

`/v1/plan` APIs respond with HTTP code 503, when plan is Pending or InProgress, to assist Marathon in determining state of DC/OS Services. 

Because of above when `/v1/plan` gets called to check for Backup/Restore status, it returns 503, which DCOS http module (which is used by Cassandra's cli module) doesn't like, so it throws an Exception.

This PR performs correct error handling, so that users can still see plan status even when it's pending or is in progress.

### CODE REVIEW

**Comment by mohitsoni** [comment]
@mesosphere-ci Please retest this.

**Comment by mohitsoni** [comment]
@mesosphere-ci Please retest this

**Comment by mohitsoni** [comment]
please retest this

**Comment by kow3ns** [comment]
Merged

**Pull request merged**
