### PR TITLE
[CASSANDRA-17] Add ability to customize offer filter refuse_seconds.

### PR DESCRIPTION
**Pull request by verma7**
Set the default to 5s so that the default behavior continues as-is.

Fixes https://dcosjira.atlassian.net/browse/CASSANDRA-17.

### CODE REVIEW

**Comment by mohitsoni** [comment]
retest this please

**Comment by mohitsoni** [comment]
@verma7 Looks good! Can you also add two unit tests for:
1. Exercising default case, when `MESOS_REFUSE_SECONDS` is not set
2. Exercising case, when `MESOS_REFUSE_SECONDS` is set

**Comment by mohitsoni** [comment]
@mesosphere-ci retest this please

**Comment by verma7** [comment]
Discussed with @mohitsoni that testing this would require changes to dcos-commons QueuedSchedulerDriver API and will be done in a later PR.

Please merge the PR when all the CI tests pass.

**Comment by mohitsoni** [comment]
@mesosphere-ci retest this please.

**Comment by mohitsoni** [comment]
@mesosphere-ci retest this please

**Comment by mohitsoni** [comment]
ok to test

**Comment by verma7** [comment]
Abandoning this as a copy #245 was merged successfully.

**Pull request closed without merging**
