### PR TITLE
Support upgrades from corrupted enum state in 1.0.19

### PR DESCRIPTION
**Pull request by mgummelt**
...after much gnashing of teeth

### CODE REVIEW

**Comment by mgummelt** [comment]
cc @nickbp for review

**Comment by mgummelt** [comment]
I'll remove most of this after 1.0.21 goes out, and document that 1.0.18 must upgrade to 1.0.20, and 1.0.19 must upgrade to 1.0.21

**Comment by verma7** [comment]
Can you explain in brief what lead to the corruption?

**Comment by mgummelt** [comment]
@verma7 This commit modified the ordinal value of the enums: https://github.com/mesosphere/dcos-cassandra-service/commit/4dae63c39f5cbd8a28bd3a7b2653c0ec5fb7f328#diff-9c78793120f905bb917f8ea26779b527

This commit fixed it https://github.com/mesosphere/dcos-cassandra-service/commit/ca9549efba7224e3ebfc6425ef77f35d7767ad2f

But we tagged 1.0.19 between the two commits https://github.com/mesosphere/dcos-cassandra-service/commit/98674cfb0ac67834131112f45c24a050db4512ec

This led to the scheduler believing that template tasks were in fact UPGRADESS tasks.

**Comment by verma7** [comment]
I think the long term fix should be to use protobufs which maintain backward/forward compatibility and can prevent these issues from happening. 

This enum used to be a protobuf (in our old version of the framework) and I don't understand why it was made into a Java Enum.

**Comment by mgummelt** [comment]
I'm not sure either.  Protobufs are a good idea.  I also just wish java supported explicit enum values like C++ does, which also would have prevented this.

**Review by nickbp — APPROVED** [review]
LGTM
Aside from the immediate fix there shouldn't be any reason to not switch back to using a protobuf enum for the `type` field. Filed #347.

**Pull request merged**
