### PR TITLE
Update dcos-commons dependency to 0.8.1.1

### PR DESCRIPTION
**Pull request by gabrielhartmann**
Consumes NPE bugfix from dcos-commons release

### CODE REVIEW

**Review by mgummelt — APPROVED** [review]

**Comment by gabrielhartmann** [comment]
@mesosphere-ci: retest this please

**Comment by gabrielhartmann** [comment]
@mesosphere-ci: retest this please

**Comment by gabrielhartmann** [comment]
retest this please

**Comment by gabrielhartmann** [comment]
retest this please

**Comment by gabrielhartmann** [comment]
retest this please

**Pull request merged**
